.TH YASMON.CONF "5" "April 2010" "YASMon 0.0.0" "User Commands"
.SH NAME
yasmon.conf \- the YASMon configuration file
.SH DESCRIPTION
Text coming soon!
.SH SEE ALSO
\fByasmon\fR(1), \fByasmond\fR(1)
.SH AUTHOR
Written by Scott Lawrence <bytbox@gmail.com>
.SH COPYRIGHT
Copyright \(co 2010 Scott Lawrence.
Licensed under the GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
.br
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
