.TH YASMOND "1" "April 2010" "YASMon 0.0.2" "User Commands"
.SH NAME
YASMond \- Yet another system monitor - server daemon
.SH SYNOPSIS
.B yasmond [-p PORT]
.SH DESCRIPTION
\fByasmond\fR hosts a simple server, providing to any client
information about the status of the computer on which the server is
being hosted. This information ordinarily includes: CPU load, memory
usage, disk usage, and a high-level overview of the activity of
various server processes.

Since anyone can connect to the server without authentication, it is
important to be sure that the information YASMon provides is not
sensitive. If the information is sensitive but YASMon must still be
used, it may be wise to hide YASMon with a firewall.

\fByasmond\fR uses the same configuration file as \fByasmon\fR
(consider it a \fByasmon\fR viewable over the network).  Since this
configuration file specifies whether local or remote mode is to be
used, in theory, one could have a \fByasmond\fR instances draw on
remote instances for information; however, this is not recommended, so
\fByasmond\fR always uses local mode, ignoring the configuration.
.SH OPTIONS
.TP
\fB\-\-version\fR
show program's version number and exit
.TP
\fB\-h\fR, \fB\-\-help\fR
show this help message and exit
.TP
\fB\-p\fR, \fB\-\-port\fR
The port on which to host the YASMon server. Default: 61874
Configuration file for YASMon client.
.SH SEE ALSO
\fByasmon\fR(1)
.SH AUTHOR
Written by Scott Lawrence <bytbox@gmail.com>
.SH COPYRIGHT
Copyright \(co 2010 Scott Lawrence.
Licensed under the GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
.br
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
