.TH YASMON "1" "April 2010" "YASMon 0.0.2" "User Commands"
.SH NAME
YASMon \- Yet another system monitor
.SH SYNOPSIS
.B yasmon
[\fI-d DELAY\fR] [\fI-l | -c\fR] [\fISERVER[:PORT] ...\fR]
.SH DESCRIPTION
\fByasmon\fR can act as a client to either a \fByasmond\fR instance
hosted on another computer, or a simulated local instance. In log mode
(\fB\-l\fR), current information about the system is periodically
printed to standard output. In curses mode (\fB\-c\fR), a top-like
ncurses interface displays current system statistics as well as
long-term averages. The default, regular or QT mode, displays
essentially the same information as curses mode but with a nicer
interface, and more visual alerts when things seem to go wrong.

For remote systems, log mode displays the server name at the beginning
of each line, without reducing the number of lines displayed for each
server. Curses mode allows the user to switch between servers. The
default mode displays brief summaries of all the servers, along with
the ability to switch between servers.
.SH OPTIONS
.TP
\fB\-\-version\fR
show program's version number and exit
.TP
\fB\-h\fR, \fB\-\-help\fR
show this help message and exit
.TP
\fB\-c\fR, \fB\-\-curses\fR
Display a curses interface
.TP
\fB\-d\fR DELAY, \fB\-\-delay\fR=\fIDELAY\fR
Delay between ordinary updates, in seconds (may be decimal).
Default: 5
.TP
\fB\-\-fs\-delay\fR=\fIFS_DELAY\fR
Delay between filesystem updates, in seconds (may be
decimal). Default: 120

There is no extra effort involved in filesystem updates - this number
is only set high by default to allow the user to view a large history
(for reasonable display widths). If YASMon is consuming too many
resources, tweak the normal delay.
.TP
\fB\-l\fR, \fB\-\-log\fR
Log events to standard output
.TP
\fB\-r\fR, \fB\-\-remote\fR 
Use remote mode, connecting to the specified servers.
.TP
\fB\-R\fR, \fB\-\-local\fR
Use local mode, not connecting to any servers. (This is the default.)
.SH SEE ALSO
\fByasmond\fR(1)
.SH AUTHOR
Written by Scott Lawrence <bytbox@gmail.com>
.SH COPYRIGHT
Copyright \(co 2010 Scott Lawrence.
Licensed under the GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
.br
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
