.TH YASMON "1" "April 2010" "YASMon 0.0.0" "User Commands"
.SH NAME
YASMon \- Yet another system monitor - server
.SH SYNOPSIS
.B yasmond

.SH OPTIONS
.TP
\fB\-\-version\fR
show program's version number and exit
.TP
\fB\-h\fR, \fB\-\-help\fR
show this help message and exit
.SH AUTHOR
Written by Scott Lawrence <bytbox@gmail.com>
.SH COPYRIGHT
Copyright \(co 2010 Scott Lawrence.
Licensed under the GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
.br
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
